### ISSUE TITLE
Right-click drop-down for with no options

### ISSUE THREAD

**Issue by Kroronos** [CEN3031-group16/GroupProject#213]
If one hovers over a right-click drop-down menu and there are no options a single unselectable option with appropriate text should be displayed.

Ex.
Right click on a user that is in every project, hovering over remove from project doesn't do anything.
Instead a box should appear that says "[Empty]" and cannot be clicked.

**Comment by Kroronos** [comment]
Example on how to do this is found: https://github.com/CEN3031-group16/GroupProject/commit/2b47879d9721377ecc4e999f17a44a886ef3f622

**Comment by tstrother** [comment]
I have the specs in this issue working, but for some reason whenever I try to remove a user from a project, it errors. Adding projects to users seems to work fine. 

Exception in thread UpdaterThread:
Traceback (most recent call last):
  File "C:\Users\Anthony\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Anthony\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\data\DataBlock.py", line 119, in updater
    self.updateAllObjects()
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\data\DataBlock.py", line 182, in updateAllObjects
    commentTable = self.conn.getData(Query.getAllComments)
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\data\ScrumblesData.py", line 64, in getData
    return queryResult.fetch_row(maxRows, how)
AttributeError: 'NoneType' object has no attribute 'fetch_row'

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\data\ScrumblesData.py", line 95, in setData
    self.dbConnection.commit()
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anthony\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\views\teamManagerView.py", line 90, in <lambda>
    lambda project=project: self.controller.dataBlock.removeUserFromProject(project, self.inspectedItem))
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\data\DataBlock.py", line 9, in wrapper
    func(self,*args)
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\data\DataBlock.py", line 335, in removeUserFromProject
    self.conn.setData(ProjectQuery.removeUser(project,user))
  File "C:\Users\Anthony\Documents\GitHub\GroupProject\source\data\ScrumblesData.py", line 98, in setData
    self.dbConnection.rollback()
_mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')

Oddly, when I use other branches and even delete the code I wrote, the program has similar issues. So I'm not sure where that is coming from.

**Comment by CEN3031-group16** [comment]
Removing user from a project was a SQL bug.  That has been resolved now.
