### ISSUE TITLE
Running Under Linux Threads do not shut down

### ISSUE THREAD

**Issue by fallinbryan** [CEN3031-group16/GroupProject#267]
background thread(s) do not shutdown running the application on the Linux OS.

Ctrl-C after exit gives the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by fallinbryan** [comment]
I really don't get it.  Logging out to switch users seems like it destroys threads.  Shutting down,  a thread stays alive, get stuck on a lock or something.  Tried updating the latest version of Python3,  tried manually deleteing threads on shutdown, nothing seems to work.  Don't understand why it works fine on windows, but not on LInux

**Comment by fallinbryan** [comment]
The latest Update that handles a loss of connection fails to work on Linux as well, indicating that there is something wrong with the socket thread..  It would appear that linux handles sockets differently, perhaps the call to a socket.read is a blocking call in linux while it is not in windows.

**Comment by fallinbryan** [comment]
That is what it was.  In linux a socket.rcv is a blocking call unless you set blocking=False.
